dist: precise
language: generic

addons:
    apt:
        sources: &sources
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
            - llvm-toolchain-precise-3.8
cache:
    apt: true

matrix:
    include:
        - os: linux
          compiler: gcc-5
          env: BUILD_FROM_SOURCES="yes" COMPILER="g++-5" BUILD_TESTS="TRUE"
        - os: linux
          compiler: clang-3.6
          env: BUILD_FROM_SOURCES="yes" COMPILER="clang++-3.6" BUILD_TESTS="TRUE"
        - os: osx
          compiler: gcc-5
          env: BUILD_FROM_SOURCES="yes" COMPILER="g++-5" BUILD_TESTS="TRUE" OPENSSL_ROOT_DIR="/usr/local/ssl"
        - os: osx
          compiler: clang-3.6
          env: BUILD_FROM_SOURCES="yes" COMPILER="clang++-3.6" BUILD_TESTS="TRUE" OPENSSL_ROOT_DIR="/usr/local/ssl"
        - os: linux
          compiler: gcc-5
          env: BUILD_FROM_SOURCES="no" COMPILER="g++-5" BUILD_TESTS="TRUE"
        - os: linux
          compiler: clang-3.6
          env: BUILD_FROM_SOURCES="no" COMPILER="clang++-3.6" BUILD_TESTS="TRUE"
        - os: osx
          compiler: gcc-5
          env: BUILD_FROM_SOURCES="no" COMPILER="clang++-3.6" BUILD_TESTS="TRUE" OPENSSL_ROOT_DIR="/usr/local/opt/openssl"
        - os: osx
          compiler: clang-3.6
          env: BUILD_FROM_SOURCES="no" COMPILER="g++-5" BUILD_TESTS="TRUE" OPENSSL_ROOT_DIR="/usr/local/opt/openssl"



before_install:
    # or another boost version
    - sudo add-apt-repository ppa:apokluda/boost1.53 --yes
    - sudo apt-get update


install:

    # or another boost version
    - sudo apt-get install libboost-system1.53-dev
    - sudo apt-get install libboost-regex1.53-dev
    - sudo apt-get install libboost-filesystem1.53-dev
    - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
    - mkdir -p "${DEPS_DIR}"
    - cd "${DEPS_DIR}"
    - |
      if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
        if [[ -z "$(ls -A ${DEPS_DIR}/cmake/bin)" ]]; then
            CMAKE_URL="https://cmake.org/files/v3.6/cmake-3.6.2-Linux-x86_64.tar.gz"
            mkdir -p cmake
            travis_retry wget --no-check-certificate --quiet -O - "${CMAKE_URL}" |
                tar --strip-components=1 -xz -C cmake
        fi
        export PATH="${DEPS_DIR}/cmake/bin:${PATH}"
      else
        if ! brew ls --version cmake &>/dev/null; then brew install cmake; fi
      fi
- mkdir build && cd build
- if [ "$BUILD_FROM_SOURCES" == "yes" ]; then
        ../tools/build_requirements.unix.sh;
  else
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      sudo apt-get update;
      sudo apt-get install libssl-dev libcurl4-openssl-dev;
    else
      brew install openssl curl pugixml;
    fi;
  fi;
