language: generic
matrix:
  include:
    - os: linux
      sudo: required
      env: COMPILER_NAME=gcc CXX=g++-5 CC=gcc-5
      addons:
        apt:
          packages:
            - g++-5
            - libboost1.55-all-dev
            - cmake
          sources: &sources
            - llvm-toolchain-precise
            - ubuntu-toolchain-r-test
            - boost-latest
install:
    - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
    - mkdir -p "${DEPS_DIR}"
    - cd "${DEPS_DIR}"
    - |
      if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
        if [[ -z "$(ls -A ${DEPS_DIR}/cmake/bin)" ]]; then
            CMAKE_URL="https://cmake.org/files/v3.6/cmake-3.6.2-Linux-x86_64.tar.gz"
            mkdir -p cmake
            travis_retry wget --no-check-certificate --quiet -O - "${CMAKE_URL}" |
                tar --strip-components=1 -xz -C cmake
        fi
        export PATH="${DEPS_DIR}/cmake/bin:${PATH}"
      else
        if ! brew ls --version cmake &>/dev/null; then brew install cmake; fi
      fi
script:
    - BUILD_DIR="${TRAVIS_BUILD_DIR}/build"
    - mkdir -p "${BUILD_DIR}"
    - cd "${BUILD_DIR}"
    - cmake -DGLOBAL_PROJECT_NAME=tester ..
    - make
    - make test ARGS="-VV"
